[build]
builder = "dockerfile"

[deploy]
startCommand = "python start_railway.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[services]]
name = "onlyai-telegram-agent"
